// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8ut3JXJ8t_tA1LueLO0PiKdrVBJDPIts',
    appId: '1:836159154817:web:ac4c792c05b1a52765fb80',
    messagingSenderId: '836159154817',
    projectId: 'firestore-b9f50',
    authDomain: 'firestore-b9f50.firebaseapp.com',
    storageBucket: 'firestore-b9f50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEEiLNgLP12BCsijxi8vlCzNXP5cYjCrk',
    appId: '1:836159154817:android:1cc3c0a1b87e935965fb80',
    messagingSenderId: '836159154817',
    projectId: 'firestore-b9f50',
    storageBucket: 'firestore-b9f50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA32VW72mLFFlaGT1n2u1_6hwouL6aWPGs',
    appId: '1:836159154817:ios:c446e51ed67401ec65fb80',
    messagingSenderId: '836159154817',
    projectId: 'firestore-b9f50',
    storageBucket: 'firestore-b9f50.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA32VW72mLFFlaGT1n2u1_6hwouL6aWPGs',
    appId: '1:836159154817:ios:eda20690562a228465fb80',
    messagingSenderId: '836159154817',
    projectId: 'firestore-b9f50',
    storageBucket: 'firestore-b9f50.appspot.com',
    iosBundleId: 'com.example.firestore.RunnerTests',
  );
}
